version: '3.8'

services:
  postgres:
    build: 
      context: ./docker/postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - backend
    restart: unless-stopped

  server:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=server
        - APP_VERSION=1.0.0
    ports:
      - "8761:8761"
    networks:
      - backend
    restart: unless-stopped

  actividades:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=actividades
        - APP_VERSION=1.0.0
    depends_on:
      - postgres
      - server
    environment:
      - SPRING_PROFILE=produccion
    networks:
      - backend
    restart: unless-stopped

  login:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=login
        - APP_VERSION=1.0.0
    depends_on:
      - postgres
      - server
    environment:
      - SPRING_PROFILE=produccion
    networks:
      - backend
    restart: unless-stopped
  
  registros:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=registros
        - APP_VERSION=1.0.0
    depends_on:
      - postgres
      - server
    environment:
      - SPRING_PROFILE=produccion
    networks:
      - backend
    restart: unless-stopped
  
  socios:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=socios
        - APP_VERSION=1.0.0
    depends_on:
      - postgres
      - server
    environment:
      - SPRING_PROFILE=produccion
    networks:
      - backend
    restart: unless-stopped

  sociosexcel:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=sociosexcel
        - APP_VERSION=1.0.0
    depends_on:
      - postgres
      - server
    environment:
      - SPRING_PROFILE=produccion
    networks:
      - backend
    restart: unless-stopped
  
  gateway:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=gateway
        - APP_VERSION=1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - server
    networks:
      - backend
    restart: unless-stopped

  # Frontend
  frontend:
    build: 
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - frontend
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  postgres-data: