version: '3.8'

services:
  server:
    container_name: server
    build: 
      context: .
      dockerfile: server/Dockerfile
      args:
        - APP_NAME=server
        - APP_VERSION=1.0.0
    ports:
      - "8761:8761"
    networks:
      - backend
    environment:
      - HOST_IP=${HOST_IP:-localhost}

  actividades:
    container_name: actividades
    build: 
      context: .
      dockerfile: actividades/Dockerfile
      args:
        - APP_NAME=actividades
        - APP_VERSION=1.0.0
    ports:
      - "8082:8082"
    depends_on:
      - server
    environment:
      - SPRING_PROFILE=produccion
      - HOST_IP=${HOST_IP:-localhost}
    networks:
      - backend

  login:
    container_name: login
    build: 
      context: .
      dockerfile: login/Dockerfile
      args:
        - APP_NAME=login
        - APP_VERSION=1.0.0
    ports:
      - "8081:8081"
    depends_on:
      - server
    environment:
      - SPRING_PROFILE=produccion
      - HOST_IP=${HOST_IP:-localhost}
    networks:
      - backend
  
  registros:
    container_name: registros
    build: 
      context: .
      dockerfile: registros/Dockerfile
      args:
        - APP_NAME=registros
        - APP_VERSION=1.0.0
    ports:
      - "8085:8085"
    depends_on:
      - server
    environment:
      - SPRING_PROFILE=produccion
      - HOST_IP=${HOST_IP:-localhost}
    networks:
      - backend
  
  socios:
    container_name: socios
    build: 
      context: .
      dockerfile: socios/Dockerfile
      args:
        - APP_NAME=socios
        - APP_VERSION=1.0.0
    ports:
      - "8083:8083"
    depends_on:
      - server
    environment:
      - SPRING_PROFILE=produccion
      - HOST_IP=${HOST_IP:-localhost}
    networks:
      - backend

  sociosexcel:
    container_name: sociosexcel
    build: 
      context: .
      dockerfile: sociosexcel/Dockerfile
      args:
        - APP_NAME=sociosexcel
        - APP_VERSION=1.0.0
    ports:
      - "8084:8084"
    depends_on:
      - server
    environment:
      - SPRING_PROFILE=produccion
      - HOST_IP=${HOST_IP:-localhost}
    networks:
      - backend
  
  gateway:
    container_name: gateway
    build: 
      context: .
      dockerfile: gateway/Dockerfile
      args:
        - APP_NAME=gateway
        - APP_VERSION=1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - HOST_IP=${HOST_IP:-localhost}
    networks:
      - backend

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_HOST=${HOST_IP:-localhost}
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NODE_ENV=production
      - HOST_IP=${HOST_IP:-localhost}

networks:
  backend:
    driver: bridge

volumes:
  postgres-data: