version: '3.8'

services:
  postgres:
    container_name: postgres
    build: 
      context: ./docker/postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - backend

  server:
    container_name: server
    build: 
      context: .
      dockerfile: server/Dockerfile
      args:
        - APP_NAME=server
        - APP_VERSION=1.0.0
    ports:
      - "8761:8761"
    networks:
      - backend

  actividades:
    container_name: actividades
    build: 
      context: .
      dockerfile: actividades/Dockerfile
      args:
        - APP_NAME=actividades
        - APP_VERSION=1.0.0
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - server
    environment:
      - SPRING_PROFILE=produccion
    networks:
      - backend

  login:
    container_name: login
    build: 
      context: .
      dockerfile: login/Dockerfile
      args:
        - APP_NAME=login
        - APP_VERSION=1.0.0
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - server
    environment:
      - SPRING_PROFILE=produccion
    networks:
      - backend
  
  registros:
    container_name: registros
    build: 
      context: .
      dockerfile: registros/Dockerfile
      args:
        - APP_NAME=registros
        - APP_VERSION=1.0.0
    ports:
      - "8085:8085"
    depends_on:
      - postgres
      - server
    environment:
      - SPRING_PROFILE=produccion
    networks:
      - backend
  
  socios:
    container_name: socios
    build: 
      context: .
      dockerfile: socios/Dockerfile
      args:
        - APP_NAME=socios
        - APP_VERSION=1.0.0
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - server
    environment:
      - SPRING_PROFILE=produccion
    networks:
      - backend

  sociosexcel:
    container_name: sociosexcel
    build: 
      context: .
      dockerfile: sociosexcel/Dockerfile
      args:
        - APP_NAME=sociosexcel
        - APP_VERSION=1.0.0
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - server
    environment:
      - SPRING_PROFILE=produccion
    networks:
      - backend
  
  gateway:
    container_name: gateway
    build: 
      context: .
      dockerfile: gateway/Dockerfile
      args:
        - APP_NAME=gateway
        - APP_VERSION=1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - server
    networks:
      - backend

  # Frontend
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  postgres-data: