version: '3.8'

services:
  postgres:
    build: 
      context: ./docker/postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - backend

  eureka-server:
    build: 
      context: .
      dockerfile: eureka-server/Dockerfile
      args:
        - APP_NAME=eureka-server
        - APP_VERSION=1.0.0
    ports:
      - "8761:8761"
    networks:
      - backend

  actividades:
    build: 
      context: .
      dockerfile: actividades/Dockerfile
      args:
        - APP_NAME=actividades
        - APP_VERSION=1.0.0
    depends_on:
      - postgres
      - eureka-server
    environment:
      - SPRING_PROFILE=produccion
    networks:
      - backend

  login:
    build: 
      context: .
      dockerfile: login/Dockerfile
      args:
        - APP_NAME=login
        - APP_VERSION=1.0.0
    depends_on:
      - postgres
      - eureka-server
    environment:
      - SPRING_PROFILE=produccion
    networks:
      - backend
  
  registros:
    build: 
      context: .
      dockerfile: registros/Dockerfile
      args:
        - APP_NAME=registros
        - APP_VERSION=1.0.0
    depends_on:
      - postgres
      - eureka-server
    environment:
      - SPRING_PROFILE=produccion
    networks:
      - backend
  
  socios:
    build: 
      context: .
      dockerfile: socios/Dockerfile
      args:
        - APP_NAME=socios
        - APP_VERSION=1.0.0
    depends_on:
      - postgres
      - eureka-server
    environment:
      - SPRING_PROFILE=produccion
    networks:
      - backend

  sociosexcel:
    build: 
      context: .
      dockerfile: sociosexcel/Dockerfile
      args:
        - APP_NAME=sociosexcel
        - APP_VERSION=1.0.0
    depends_on:
      - postgres
      - eureka-server
    environment:
      - SPRING_PROFILE=produccion
    networks:
      - backend
  
  gateway:
    build: 
      context: .
      dockerfile: gateway/Dockerfile
      args:
        - APP_NAME=gateway
        - APP_VERSION=1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - backend

  # Frontend
  frontend:
    build: 
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  postgres-data: